### ISSUE TITLE
Crashes when playing a song and scrolling

### ISSUE THREAD

**Issue by seaweede** [Superjo149/auryo#107]
Using Auryo 2.0.2 64-bit portable (although the error persisted in the non-portable version)
On Win10 LTSB 64-bit

When using the app if I scroll I can load songs just fine, and I can also play songs just fine too, but when a song is playing and I attempt to scroll and the app attempts to load more songs it crashes to a white screen and doesn't throw any errors at me. It happened in the 2.0.0 version too but it happens every time I play/scroll now rather than rarely.

Still love the app and what you've done with the updates, thank you for your hard work!

UPDATE:

Got an error window and copied it.
`Unhandled Error
Error: Value to set is of unexpected type
    at on (C:/Auryo/resources/app.asar/webpack:/src/main/features/win32/win10/Win10MediaService.js:89:137)
    at EventEmitter.<anonymous> (C:/Auryo/resources/app.asar/node_modules/electron-router/router.js:216:20)
    at WebContents.<anonymous> (C:/Auryo/resources/electron.asar/browser/api/web-contents.js:286:13)
    at WebContents.emitter.emit.args [as emit] (C:/Auryo/resources/app.asar/node_modules/@sentry/electron/src/main/backend.ts:378:14)`

**Comment by seaweede** [comment]
Thank you! No rush, you do amazing work!

**Comment by kostadinnm** [comment]
Just to add my input as well: I'm having the issue when I play a particular song: [4 strings-Diving](https://soundcloud.com/aaron-martinez-29/4-strings-diving). I'm also using the portable version and I consistently get this error:
![2018-10-06 11_04_54-auryo](https://user-images.githubusercontent.com/18436405/46569094-e15be080-c958-11e8-8d63-4828e127941f.png)
The song continues to play, but the player is dead. Then, when I hit "Copy error", I get yet another message:
![2018-10-06 11_05_09-auryo](https://user-images.githubusercontent.com/18436405/46569111-04869000-c959-11e8-87f7-6bcfc1961f08.png)
Hope this helps.
Cheers,
Kostadin

**Comment by Superjo149** [comment]
I found the cause of this. The past 2 weeks i've been rewriting the code to remove some of these nasty bugs. I'll keep u posted.
