### ISSUE TITLE
MPRIS seems to have broken again in v2.1.0

### ISSUE THREAD

**Issue by Superjo149** [Superjo149/auryo#108]

**Comment by yebo29** [comment]
playerctl times out:
`playerctl -p auryo-player pause
Could not execute command: Timeout was reached`

**Comment by N33G** [comment]
Since 2.4.0 on the deb and appimage versions im unable to control auryo using the plasmoid on plasma 5.15. Was able to replicate this same issue by using playerctl as described in this issue. Version 2.3.3. works as expected. Since this is an old issue should i open a new one?

**Comment by Superjo149** [comment]
@N33G No it's fine. It's the same issue. When I try to activate global shortcuts using dbus for ubuntu, MRPIS breaks.

**Comment by Superjo149** [comment]
Fixed in 2.5.0, player renamed to `auryo_player`
