### ISSUE TITLE
Options bar appears when starting track.

### ISSUE THREAD

**Issue by glaere** [Superjo149/auryo#120]
An options bar at the top (view, edit, playback, etc) appears but only when starting a track. Also has a weird gap between Discover and the top (search is in the top middle and user on the top right at same level).

Maybe get rid of the options bar and iconise it? Standard seems to be three horizontal bars.

Ubuntu 18.04.1
Auryo 2.1.1 snap
![auryo_bug_option_bar](https://user-images.githubusercontent.com/1971723/45128303-38617080-b175-11e8-805f-b8b782813296.png)

Thanks in advance.

**Comment by Superjo149** [comment]
Gap is fixed, will be included in next update, this was for mac window control overlay. 

I know the menubar looks kinda ugly, but it's the default application menu. Not sure if and how I'm going to make it better.
