### ISSUE TITLE
Soundcloud Go+ musics does not appear on likes

### ISSUE THREAD

**Issue by Srywards** [Superjo149/auryo#126]

**Comment by Superjo149** [comment]
Third party apps unfortunately do not have access to GO+ music.

**Comment by Srywards** [comment]
> Third party apps unfortunately do not have access to GO+ music.

Why exactly ?

**Comment by Superjo149** [comment]
Sorry, I am wrong in this. As for all music on the SoundCloud platform. Publishers are able to deny access via external api (which we use). Not sure why SoundCloud has this feature, but that's why some free music and GO+ is not visible in the app.

**Comment by Srywards** [comment]
Thanks for the reply ;)
