### ISSUE TITLE
Can't start playing music when i click on the playlist directly

### ISSUE THREAD

**Issue by Srywards** [Superjo149/auryo#130]
When I click on the playlist nothing happens, I'm forced to enter this one and click on the first sound to launch the playlist

**Comment by Srywards** [comment]
Nope on the left i click on playlist, my playlist appear and there is a button on it : https://goopics.net/i/NaPng
If i click on it nothing happens

**Comment by Srywards** [comment]
After the update in 2.2.0 I still have the same problem

**Comment by Superjo149** [comment]
Is it only happening with the specified playlist above? And what page is this happening on?

**Comment by Superjo149** [comment]
I've added the above mentioned playlist to my playlist and I can't seem to be able to reproduce this issue. (Nice music btw)

There must some other faulty playlist there causing mayhem. I think I can narrow it down and fix it, but then I don't know what caused it. Could you share the playlists you have there? Either here or via email? Or is there too many?

**Comment by Superjo149** [comment]
Or if you want, you can go into the chrome inspector of the app and send me the JSON output you received. But this required a couple more steps.

**Comment by Srywards** [comment]
Yes Beauvois is nice :)
I can try to send you the JSON, explain me how to do this and i'll send to you

**Comment by Srywards** [comment]
Done

**Comment by Superjo149** [comment]
Allright, fixed it. Pretty nasty bug, I'm glad you encountered this. This brought some other bugs to the surface. All will be resolved in the 2.2.1 🎉

**Comment by Superjo149** [comment]
Allright, it's published. You may notice some slower initial speeds on loading a list of large playlists, but it works. All that logic still needs some refactoring & perf tweaking.

**Comment by Srywards** [comment]
It works ! Thank you a lot, i haven't noticed the slowdown as you told me :)
