### ISSUE TITLE
Ubuntu budgie desktop locks up when auryo is visible

### ISSUE THREAD

**Issue by Mindgamesnl** [Superjo149/auryo#135]
Hey There,
I noticed that the Ubuntu Budgie desktop tends to lock up while Auryo is visible (window does not require focus to trigger this issue). 

behaviour:
 * The application windows does not respond (no response on mouse click and windows/super key)
 * Settings side bar becomes unresponsive
 * Notification side bar becomes unresponsive
 * Notifications do not trigger (example, discord, slack and whatsapp)

proof and example can be found here: https://www.youtube.com/watch?v=eoutHRB_khw&feature=youtu.be

My ubuntu budgie version is based on Ubuntu 10.04.1 LTS (https://gyazo.com/537e004df4b869af5e9df2241d9f267e)

And i run Auryo version 2.1.2 (https://gyazo.com/41fca111ed083f16b757d33d5666562b)

Besides this kinda annoying bug i really like Auryo so far and hope to see more of this project in the future :)

**Comment by Superjo149** [comment]
Might be related to #108, will look into it for 2.2
