### ISSUE TITLE
Search doesn't work with UTF-8 text ?!

### ISSUE THREAD

**Issue by drupalshift** [Superjo149/auryo#137]
_- Which OS was your using?_

**Operating System: Manjaro Linux 
KDE Plasma Version: 5.14.1
Kernel Version: 4.17.19-1-MANJARO**

_- Which version of Auryo were you using?_

**aur package** `auryo-bin 2.1.2-2`
**which is based on** `auryo-2.1.2.pacman`

_- Where did this error happen?_

**Doesn't spit any error, 
Simply search doesn't work when you try to search UTF-8 encoded text** 

_- What steps did you take to receive this error?_

**Try to search any of this strings which are valid and you can find using SoundCloud**
`你好` `سلام` `שלום` `नमस्ते`

**Comment by Superjo149** [comment]
Already fixed in #136 , I'm just going to add a couple more features and fix a few more bugs before I release it.
