### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Superjo149** [Superjo149/auryo#141]
Not sure what the best way is to implement this. Maybe with React Context?

**Comment by Superjo149** [comment]
Duplicate of #97

**Comment by Secr3ts** [comment]
It has been implemented ?

**Comment by Superjo149** [comment]
No it has not, unfortunately. I just referenced it because it when refactoring scss, we should consider making it easy for implementing this in the near future.

**Comment by Secr3ts** [comment]
ye i saw that. thanks again for auryo i love it!
