### ISSUE TITLE
Auryo - Unhandled Error - Error: Value to set is set of unexpected type

### ISSUE THREAD

**Issue by RedYoshikira** [Superjo149/auryo#147]
<!--
![image](https://user-images.githubusercontent.com/7945427/48141118-305aa580-e278-11e8-8f16-21bc1167f745.png)

See screenshot above to view the error.

- OS: Windows 10 x64 Home - Standard User, Non-UAC

- Auryo Version: Auryo x64-bit Portable - Windows v.2.1.2

- During song playback.

- This error happens when I play a certain track, then the main interface closes, the error shows, however playback of current and next-up songs play normally. Once the error box is closed, the rest of Auryo's playback ends as well.

**Comment by RedYoshikira** [comment]
Update: The issue appears to resolve itself if you remove, then re-add the song from your playlist/likes.

**Comment by Superjo149** [comment]
This is fixed in v2.2.0. I'll be pushing the update between this and a couple of days. 😄
