### ISSUE TITLE
Add Soundcloud Weekly in Discover

### ISSUE THREAD

**Issue by Srywards** [Superjo149/auryo#154]
Hello,

Just after charts on auryo can you add Soundcloud Weekly ?

![discover](https://user-images.githubusercontent.com/15232456/48416950-cb102400-e751-11e8-8fb7-dafa930d82ac.png)

On official soundcloup it's like that :
![weekly](https://user-images.githubusercontent.com/15232456/48417002-f7c43b80-e751-11e8-8e22-e014a3d23bb0.png)

Thanks !

**Comment by Superjo149** [comment]
I would love to add this. This is something I wanted to include in #143. Unfortunately SoundCloud doesn't offer a public API for this and your aren't really supposed to use their internal APIs (I already do this for some things). 
So I'm still debating whether I want to risk this or not. I don't want to lose my keys.

**Comment by Srywards** [comment]
Why you can not use their internal API ?

**Comment by Superjo149** [comment]
https://stackoverflow.com/a/29258809

**Comment by Superjo149** [comment]
I've tried adding the weekly playlist using the new URL resolve feature in the search bar of Auryo. But unfortunately that doesn't work.

**Comment by Superjo149** [comment]
Added in 2.3.0
