### ISSUE TITLE
Playlist titles extend to infinity to the right

### ISSUE THREAD

**Issue by osamadel** [Superjo149/auryo#157]
# 🐛 Bug report

## What issue are you facing
After the latest update, the **Playlist** view, which displays all the playlists that I liked, displays the titles of individual playlists without a boundary. The text extends to the right over next playlists. Here is an image:
![auryo_issue](https://user-images.githubusercontent.com/5947722/48622404-5508f880-e9af-11e8-85a4-5b5acfc716ae.png)

## Steps to reproduce

Closed an re-opened the app several times. It happens only in the **Playlists** view not in the **Likes** or **Tracks**.

#### Which Operating System? 

Ubuntu 18.04 LTS

#### Which version of Auryo? 
Version: Auryo 2.2.1
Platform: Linux
Platform Version: 4.15.0-39-generic
Arch: x64

**Comment by Superjo149** [comment]
Reopening this as it has not been released yet.
