### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by LiveNL** [Superjo149/auryo#160]
# 🐛 Bug report

## What issue are you facing
As there's a new update I would like to download it from the website but it appears to be down.

## Steps to reproduce
```
$ curl http://auryo.com
curl: (56) Recv failure: Operation timed out
```

## Environment
Various browsers + command line

#### Which Operating System? 
macOS Mojave

#### Which version of Auryo? 
Not relevant.

**Comment by Superjo149** [comment]
All fixed, I'm having some issues with a memory leak.

**Comment by LiveNL** [comment]
Thanks 👏

**Comment by LiveNL** [comment]
It might be worth to mention that the website is pointing to the 2.2.1 release (although 2.2.2 is made available).

**Comment by Superjo149** [comment]
Ah yes, thanks for letting me know. I haven't added the new website to my design flow yet.
