### ISSUE TITLE
Play/Pause not caught on Ubuntu 18.10 with mate

### ISSUE THREAD

**Issue by dennorske** [Superjo149/auryo#163]
**A quick summary and/or background**: I am running Ubuntu 18.10 with Mate desktop environment on top. Media key "Play/Pause" on my keyboard is not caught by Auryo sadly (it is in Ubuntu). So I am unable to play/pause my songs with my keyboard/headset.

**Steps to reproduce**: Open Auryo, press play/pause. No reaction. Try with Spotify or other apps, and this works. I expected Auryo to catch the keypress and process it so I can play music using Mate as well.

**Other**: I've been trying my best to change shortcuts in the distro, however, all keypresses show up normally while debugging in a terminal.

**Comment by Superjo149** [comment]
Ah yes, I tried adding this previously , but it broke MPRIS. I'll see what I can do about that.

**Comment by dennorske** [comment]
Ah I see. Thanks for the quick reply, this would be really cool if added without issues. Let me know if I can be of more help to you.

**Comment by alexkohler** [comment]
I am also running into this issue on Ubuntu 14.04 and Gnome.

**Comment by dennorske** [comment]
Any update on this, are there other things i could help out with?
