### ISSUE TITLE
Showing notifications even with option turned off

### ISSUE THREAD

**Issue by oscarnydza** [Superjo149/auryo#165]
# 🐛 Bug report

## What issue are you facing

Just as the title suggests. It still pushes notifications on the panel even though the option is ticked off in the Options menu.

## Steps to reproduce

Just turned the option off. Looks like if ticked on and off again it works for a while, but then it starts showing notifications in the panel again.

#### Which Operating System? 

Ubuntu 18.04 Cinnamon 3.6.7, kernel version 4.19.0

#### Which version of Auryo? 
Auryo version 2.3.1, though I haven't tested in any other versions since I just discovered this option.

**Comment by Superjo149** [comment]
Could you try restarting the app?

**Comment by oscarnydza** [comment]
Tried it and it still happens. I also tried switching to the workspace in which is executing and it worked properly.

**Comment by N33G** [comment]
Found the same behavior on the Snap version 2.3.1 under Neon 5.14. Closing the app wont save the changes on the notification slider the other ones seem to be working as expected.

**Comment by Superjo149** [comment]
Is the option turning back on after restart?

**Comment by oscarnydza** [comment]
In my case it does turn back on after the application is restarted.

**Comment by Superjo149** [comment]
probably related to #179
