### ISSUE TITLE
Add Cast 

### ISSUE THREAD

**Issue by frani** [Superjo149/auryo#169]
# 💡 Feature request

## What do you propose
Sometimes I want to hear the music on my ChromeCast, I think that you can add that feature.

## Whats steps can we take to implement it
I found this git: https://github.com/GPMDP/electron-chromecast
I think it could help!

**Comment by Superjo149** [comment]
Yes would be very nice, but it's a duplicate of #99, so I'll be closing this one. Thanks for the link.
