### ISSUE TITLE
cant use

### ISSUE THREAD

**Issue by gudge25** [Superjo149/auryo#170]
# 🐛 Bug report

## What issue are you facing
I cant use app 

## Steps to reproduce
install last deb app   -> launch --> press login

## Environment
on my Linux OS 

#### Which Operating System? 
Linux mint 18.3 x64

#### Which version of Auryo? 
2.3.1

![screenshot_2019-01-10_15-37-56](https://user-images.githubusercontent.com/2346208/50971839-bbad1d00-14ed-11e9-87e9-89d8c3c909d6.png)

**Comment by alexisaguilar** [comment]
Same problem
-------------------------------------------------
> #  Bug report
> ## What issue are you facing
> I cant use app
> 
> ## Steps to reproduce
> install last deb app -> launch --> press login
> 
> ## Environment
> on my Linux OS
> 
> #### Which Operating System?
> Linux mint 18.3 x64
> 
> #### Which version of Auryo?
> 2.3.1
> 
> ![screenshot_2019-01-10_15-37-56](https://user-images.githubusercontent.com/2346208/50971839-bbad1d00-14ed-11e9-87e9-89d8c3c909d6.png)

**Comment by Superjo149** [comment]
Looking into it now.

**Comment by Superjo149** [comment]
Fixed
