### ISSUE TITLE
Next up menu and current playlist differs from website playlist

### ISSUE THREAD

**Issue by N33G** [Superjo149/auryo#172]
# 🐛 Bug report

## What issue are you facing

The menu next up and the auryo playlist being shown "seems" to differ from the actual soundcloud content. Sort order / track number not respected.

## Steps to reproduce

1. Start streaming music from an existing playlist. 
2. Compare the actual list shown on Auryo vs the next up menu.

## Example
To replicate the current playlist chill under soudcloud.com "Gentle Dreams 🛏️ - An Indie/Chill/Electronic Playlist" was choose and duplicated by just taking the first 8 tracks.

This is how it looks on the website.

![sclistclone](https://user-images.githubusercontent.com/46009354/51076926-ee464980-1696-11e9-9c29-47971c5bfdc4.png)

This is how Auryo displays the playlist no play button clicked.

![auryolist1](https://user-images.githubusercontent.com/46009354/51077119-c5738380-1699-11e9-87d1-844c8819229d.png)

After the play button is clicked.

![auryolist2](https://user-images.githubusercontent.com/46009354/51077167-724e0080-169a-11e9-83d4-6884fbd2feca.png)

As it can be seen the playlist is in wrong sort order compared to the website. From what i can see Auryo sorts the songs on alphabetical order but by pressing start the first song (number 1) on soundcloud website plays the track but is no longer the track no.1on Auryo making Auryo practically skip half the playlist.  (But for whatever reason the track no.1 doesn't follow the order inside the next up menu)

This is a bit confusing and gets a bit worse when songs with limit on third party apps get in to the mix.

Auryo should follow the current sort order of the playlist on soundcloud always. I will post another bug that makes example of that.

Note: Searching the original playlist will show that Auryo is capable of showing the current playlist correctly it seems to be related only to user created playlists.

#### Which Operating System? 

Linux

#### Which version of Auryo? 

 Deb and Snap version 2.3.1

**Comment by Superjo149** [comment]
I love how detailed this issue is. ❤️ I'll look into it.
