### ISSUE TITLE
Adding a new song to an existing playlist breaks sort order on both ends

### ISSUE THREAD

**Issue by N33G** [Superjo149/auryo#173]
# 🐛 Bug report

## What issue are you facing

Adding a new song to an existing playlist through Auryo breaks the sort order on both Auryo and the original playlist on soundcloud.

This is related to the bug   #172

## Steps to reproduce

1. Add a song to a playlist using Auryo.
2. Compare the playlist on soundcloud and on Auryo after a restart.

[This is the original playlist from the first bug](https://user-images.githubusercontent.com/46009354/51076926-ee464980-1696-11e9-9c29-47971c5bfdc4.png) from #172.

By adding  a new track (no. 9 from the chill playlist) to the playlist will make soundcloud display this.

![sclistclonewrong](https://user-images.githubusercontent.com/46009354/51077954-abd83900-16a5-11e9-83de-c7ef2edfd649.png)

It seems to follow the same alphabetical order but this time the last song goes to the first spot adding more songs just makes the sort order messier.

So i will not recommend trying to replicate this on an existing playlist more if its considerably long.

Remember having this problem by trying Auryo before it went Open-source but until recently i was not able to find and replicate the sorting order detail. Hope this information helps.

#### Which Operating System? 

Linux

#### Which version of Auryo? 

Deb and Snap version 2.3.1

**Comment by Superjo149** [comment]
I see, I'm also now realising it removes items from the playlist which are not visible in Auryo. This is all because of some recent changes.

**Comment by Superjo149** [comment]
Hmmm, yes this is the case. That's very annoying.

**Comment by Superjo149** [comment]
I'll have to completely disable adding tracks to playlists. Since we need to send all ids of the tracks in the playlist, we cannot know for sure if there are tracks hidden for us.

**Comment by N33G** [comment]
Yes indeed one of the reasons i stopped trying to replicate and just used the dummy on the example playlist was because i had no idea what was happening. Since is difficult to compare both lists since the order/number of songs is not the exactly the same.  My first thought while doing this the first time  was maybe i deleted some songs.
