### ISSUE TITLE
Timed out, login took longer than expected

### ISSUE THREAD

**Issue by Dumbledorf** [Superjo149/auryo#175]
# 🐛 Bug report

## What issue are you facing
When I try to log in the request takes too long. I know for a fact that it has nothing to do with my internet connection as I can login to every other application and website without a problem.

## Steps to reproduce
Open up the program and try to log in.

## Environment
GNOME Shell 3.28.3

#### Which Operating System? 
Ubuntu 18.04 Bionic Beaver LTS

#### Which version of Auryo? 
2.3.1

**Comment by moigagoo** [comment]
I'm having the same issue on Ubuntu 18.10, installed via Software Center.

**Comment by Superjo149** [comment]
Allright, I'm pretty busy. But I'll try and have a look tomorrow.

**Comment by moigagoo** [comment]
Installing from .deb works just fine though, so it's not a critical issue.

**Comment by Superjo149** [comment]
@moigagoo hmm, so possibly an issue with the snap binaries.

**Comment by Superjo149** [comment]
It seems to be working for me. But it requires a few tries. I'll try and look further into this as to why this is happening.

**Comment by Dumbledorf** [comment]
It works for me now. I haven't done anything to fix it though. That's odd.

**Comment by Superjo149** [comment]
Hmm, maybe the authentication server was under a high load. I'm not sure why this is. I added some extra logging in the next patch to try and find the cause.
