### ISSUE TITLE
Play/pause from Windows taskbar thumbnail desyncs from actual playback state

### ISSUE THREAD

**Issue by vith** [Superjo149/auryo#180]
# 🐛 Bug report

## What issue are you facing
Often the pause button on the thumbnail works, but doesn't change to a play button afterwards. In some cases I've become unable to restart playback from the main GUI either. Waiting a while and checking again, sometimes the thumbnail's button has changed.

## Steps to reproduce
Alternate between clicking the play/pause button in the main GUI and the one on the taskbar thumbnail.

#### Which Operating System? 
Windows 10 1803

#### Which version of Auryo? 
2.3.3

**Comment by Superjo149** [comment]
I think I accidentally came across this bug in my code. I'll be testing it and it should be shipping in 2.4.0
