### ISSUE TITLE
[Bug] Endless Login

### ISSUE THREAD

**Issue by sTiKyt** [Superjo149/auryo#181]
# 🐛 Bug report

## What issue are you facing

I can't login, i just have this on my screen:
![Selection_023](https://user-images.githubusercontent.com/35602029/54070632-f4a60b80-426a-11e9-91e1-fdd1e7db6146.png)

## Steps to reproduce
Installed Auryo using AUR > Opened it > Press login > Logined using Webpage > got info and ability to start > press start button > Got endless loading

## Environment

Cinnamon, latest.
#### Which Operating System? 

Platform: linux x86_64
Distribution: Arch Linux
Kernel Release: 4.20.12-arch1-1-ARCH

#### Which version of Auryo? 
v2.3.3

#### Additional Screenshots
![image](https://user-images.githubusercontent.com/35602029/54070699-e73d5100-426b-11e9-8aba-74f95fc7ca62.png)
![image](https://user-images.githubusercontent.com/35602029/54070705-ff14d500-426b-11e9-8ccf-ab535f340b0e.png)
![image](https://user-images.githubusercontent.com/35602029/54070711-0b992d80-426c-11e9-80d6-e63de55feb15.png)

**Comment by BobCrawls** [comment]
This happens on Windows too.

**Comment by Superjo149** [comment]
Hmm, I'll look into it now.

**Comment by BobCrawls** [comment]
> Hmm, I'll look into it now.

Thanks mate

**Comment by BobCrawls** [comment]
Better gif https://i.novuscommunity.co/WfdLJZ.gif

**Comment by Superjo149** [comment]
It's not an easy one to reproduce unfortunately. Are you able to launch Auryo via command line with arguments `--dev`?

**Comment by BobCrawls** [comment]
> It's not an easy one to reproduce unfortunately. Are you able to launch Auryo via command line with arguments `--dev`?

https://i.novuscommunity.co/2dhjOv.gif

**Comment by BobCrawls** [comment]
I hope I did that right

**Comment by BobCrawls** [comment]
Running it in administrator mode fixed it

**Comment by BobCrawls** [comment]
Works now

**Comment by Superjo149** [comment]
Hmm, that's weird. Are there any restrictions on the normal user?

**Comment by BobCrawls** [comment]
Nope. This is the only user on this pc as it is administrator

**Comment by gitsper** [comment]
@sTiKyt I had the same problem as you (same exact steps to reproduce, also on arch linux). I found that removing the [auryo](https://aur.archlinux.org/packages/auryo) package and instead using the [auryo-bin](https://aur.archlinux.org/packages/auryo-bin/) package works for me.

**Comment by Superjo149** [comment]
@gitsper @sTiKyt auryo-bin is the one you should be using as this is the one I am maintaining.

**Comment by sTiKyt** [comment]
Wow, it was 2019 and i just got notification.. R.I.P. GitHub notifications
