### ISSUE TITLE
Can not read property 'indexOf' of null 

### ISSUE THREAD

**Issue by dzuykhanh** [Superjo149/auryo#191]
# 🐛 Bug report

## What issue are you facing
 Auryo can not start, it always show Can not read property 'indexOf' of null as in the screeshot. 
https://i.imgur.com/VFYa4He.png

I pressed reload many times, but it stayed still, nothing changes. 

#### Which Operating System? 
 I'm using Elementary OS Juno. 

#### Which version of Auryo? 
I'm using Auryo 2.4, .deb version.

**Comment by Superjo149** [comment]
Do you know where this error happened of what you did to encounter it?

**Comment by rlimaeco** [comment]
I have the same problem :/
Using Manjaro KDE

![image](https://user-images.githubusercontent.com/1217117/56219584-61b47a00-603d-11e9-8fe2-db162a007995.png)

**Comment by bryguy** [comment]
This happens to me every time I click on the "For you" section:

<img width="978" alt="Screen Shot 2019-04-23 at 10 43 57 AM" src="https://user-images.githubusercontent.com/1933777/56603589-d5620400-65b4-11e9-93d8-74683ccdaad6.png">

I got around it by clicking on a different section and then refreshing.

If it helps, I'm on macOS 10.14.3.

**Comment by smaznet** [comment]
i have this problem too

**Comment by Superjo149** [comment]
Thanks fot letting me know. I'll try to push the new update ASAP. I've currently been sidetracked by other projects.

**Comment by thephoenix01** [comment]
Hi, the same is still happening to me in Manjaro XFCE.

**Comment by miningmanna** [comment]
I cant use the application at all.
Refreshing it in different tabs does nothing.

Do you have a debug option?

**Comment by robojones** [comment]
I am still getting the same error message. I've tried to .deb and .appimage versions.

**Comment by Superjo149** [comment]
Upcoming version will fix this. :)

Op 20 aug. 2019 21:00 schreef Jonathan Scholz <notifications@github.com>:

I am still getting the same error message. I've tried to .deb and .appimage versions.

**Comment by robojones** [comment]
@Superjo149 That's great to hear! When can we expect a version with this fix? :smiley:

**Comment by mshzsh** [comment]
i have this problem too when click on 'For you' section.
i use elementary Juno, and installed with .deb file

**Comment by webmastak** [comment]
The same error, the reload button does not help. It’s necessary to start and close the program corny until it boots normally and it can be 5 times or more. :(

**Comment by robojones** [comment]
I still have the error every I open the app time. Auryo is unusable for me. @Superjo149 is there any progress?

**Comment by webmastak** [comment]
Oddly enough, my error disappeared.

**Comment by dishcandanty** [comment]
Still seeing this on 2.5.2 :/
