### ISSUE TITLE
"Cannot read property 'username' of underfined" when opening Settings

### ISSUE THREAD

**Issue by Nilskachu** [Superjo149/auryo#193]
# 🐛 Bug report

## What issue are you facing

When I open the Settings page while beeing on a song page I see a white site with a error message:
![error message](https://user-images.githubusercontent.com/31930689/55743717-55279480-5a33-11e9-8fdf-c486620519eb.png)
The reload button doesn't work and I have to restart the applicaton manually to use it again.

## Steps to reproduce

Open any song page (tap the title) -> click on the three dots on the right top next to the username and select 'Settings'

#### Which Operating System? 

Arch Linux (Kernel 5.0.5-arch1-1-ARCH)

#### Which version of Auryo? 
2.4.0
![Screenshot_20190408_191127](https://user-images.githubusercontent.com/31930689/55744059-3e357200-5a34-11e9-83f9-3157715eee6a.png)

**Comment by N33G** [comment]
Yeah im able to replicate the same on  2.4.0 appimage. Not only that all the right options (playlists,likes,etc) are disabled along the navigation arrows until the app is restarted.

**Comment by Superjo149** [comment]
This has already been fixed but I'm waiting until I have some more time to finish this update. It'll also include dark mode & chromecast support.
