### ISSUE TITLE
How does the clientId look like on the inspector?

### ISSUE THREAD

**Issue by EmmanuelMess** [Superjo149/auryo#194]
I am on Firefox and haven't found any "clientId" parameters, if you could add to the wiki what packets contain it, or if it is stored in cookies it would be helpful.

Thank you for your time.

**Comment by Superjo149** [comment]
You can just goto the network tab and copy it from one of the requests to the api-v2.soundcloud.com urls. Another option would be to use the chrome extension. https://github.com/Superjo149/auryo/wiki/Custom-clientId
