### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by mr-ezak** [Superjo149/auryo#195]
# 🐛 Bug report

## What issue are you facing

Every time I start the app it shows me an error and it says: "Failed to fetch".
![Screenshot from 2019-05-21 00-01-22](https://user-images.githubusercontent.com/28624243/58046805-9d21f700-7b5b-11e9-8a86-2c817a83b493.png)

## Steps to reproduce

All I did was that I set up the proxy setting on the auryo setting section.
#### Which Operating System? 

Ubuntu 18.04
#### Which version of Auryo? 
2.4.0

**Comment by mr-ezak** [comment]
All I'm asking for is to show me a way to reset all of my app settings, Where can I find the auryo configuration file on my ubuntu and remove the proxy that I set up before.

**Comment by Superjo149** [comment]
You can find and delete this at `~/.config/Auryo/Settings`. Unfortunately, I haven’t been able to thoroughly test the proxy feature since I do not have access to one, hence the experimental tag. My apologies for the inconvenience.

**Comment by mr-ezak** [comment]
Thank you very very much, Problem completely Solved.

**Comment by mr-ezak** [comment]
You said that you don't have access to a proxy to test your apps proxy setting feature, I think you can use "Tor service" to test that.
For example in Ubuntu: All you have to do is to install Tor with "sudo apt install tor", And after that, you can use 127.0.0.1:9050 as your proxy. It's fast and free and safe, I've been using it for years and it's been quite useful.

**Comment by Superjo149** [comment]
Oh nice. I'll look into that. Thanks.
