### ISSUE TITLE
Login problem on SoundCloud - Redirect_URI_Mismatch

### ISSUE THREAD

**Issue by Butonator** [Superjo149/auryo#197]
Hi team,

when I try to login on Auryo app and I am redirected on SoundCloud I get this error:

![image](https://user-images.githubusercontent.com/27275004/58091726-a5654b00-7bca-11e9-98df-e778333b7d47.png)

I tried this on IE, EDGE, Chrome and everywhere is the same problem.

What should I do? Is there any workaround for this?

Thanks a lot. You APP is the best!!!

Tony

**Comment by Superjo149** [comment]
Hi, thanks for creating this issue.

I'm aware of this. I'm preparing some changes to the way I handle logins in the future. For this I asked SoundCloud to make some changes to my configuration. I'm trying to resolve this with them, but this may take some time. I'm hoping for it to be resolved by tomorrow. 

You can follow https://twitter.com/auryoapp for the latest info on this.

**Comment by Superjo149** [comment]
Allright, this has been resolved.
