### ISSUE TITLE
Please update Snap

### ISSUE THREAD

**Issue by fluffynuts** [Superjo149/auryo#209]
# 🐛 Bug report
Snap package is at 2.3.3 where the general release version seems to be 2.4.0?

I'm just a bit of an update ho -- I want the latest-latest of everything (:

In the meantime, I've installed the .deb -- I'd actually prefer a ppa or something similar, but I'll settle for an updated snap, if possible (:

**Comment by Superjo149** [comment]
Something changed in snap which required a manual review on their part. But this never happened. I notified them but nothing changed. I waited for the new release to bug them again.

**Comment by alculete** [comment]
please ping them again snap version is very useful

**Comment by Superjo149** [comment]
Will be followed up in #242
