### ISSUE TITLE
Entering an invalid client id in the settings pane gets the user into an infinite login loop

### ISSUE THREAD

**Issue by fluffynuts** [Superjo149/auryo#210]
# 🐛 Bug report

## What issue are you facing
I wanted to use my own client id for the app and wanted to just sniff it from my firefox network tab. I unfortunately found the _wrong_ client id (must have been for some other bit of data flowing between my browser and soundcloud), put that in, and ended up back at the login screen again. When I tried to log in again, the app gets to the landing page and then quickly takes me back to the login page, obviously because the bad client id causes a 401 on some request

I eventually sorted it by manually editing Auro/Settings -- just had to find it under AppData\Roaming\Auryo

## Steps to reproduce
Enter any invalid client id into the settings pane and enter the infinite login loop

## Environment
App version: 2.4.0
OS: Windows -- but I expect this would apply on any OS

**Comment by pozda** [comment]
same thing on macOS
