### ISSUE TITLE
Endless "something went wrong" in "For you"

### ISSUE THREAD

**Issue by EmmanuelMess** [Superjo149/auryo#221]
# 🐛 Bug report

## What issue are you facing
![Captura de pantalla de 2019-09-17 10-21-45](https://user-images.githubusercontent.com/10991116/65045390-11677e00-d935-11e9-8016-8f417225a587.png)

## Steps to reproduce
Open "For you".

## Environment
Ubuntu

#### Which Operating System? 
Ubuntu 18.04 with Unity

#### Which version of Auryo? 
2.4.0

**Comment by tolgakacmaz** [comment]
I have the same problem with Ubuntu 18.04 with KDE

**Comment by clixkode** [comment]
> I have the same problem with Ubuntu 18.04 with KDE

ditto here

**Comment by LeoDlog** [comment]
Same with windows :(

**Comment by Superjo149** [comment]
I have a fix ready, but I'm having issues build the app. Please bear with me.

**Comment by ninghaoqing** [comment]
I have the same issue in Ubuntu T T

**Comment by EmmanuelMess** [comment]
@Superjo149 any news?

**Comment by jonaslouras** [comment]
Same issue on Mint 19.3!

**Comment by doctortee** [comment]
Still not fixed

**Comment by gudge25** [comment]
same issue

**Comment by erfanium** [comment]
sameee

**Comment by prostomarkeloff** [comment]
Have got same issue

**Comment by ilyesAj** [comment]
same here on elementary os

**Comment by prostomarkeloff** [comment]
Any updates? @Superjo149

**Comment by Superjo149** [comment]
Got you covered guys.

**Comment by prostomarkeloff** [comment]
@Superjo149 Thanks!
