### ISSUE TITLE
"Something went wrong" in the For "you Tab" on windows

### ISSUE THREAD

**Issue by LeoDlog** [Superjo149/auryo#224]
# 🐛 Bug report
![image](https://user-images.githubusercontent.com/39237127/66067832-b2b51d80-e54c-11e9-8a9e-9f8258166ddb.png)

## What issue are you facing
When I click on the "For You" tab there this Error message

## Steps to reproduce
fresh install and connected to my account and when i click on "For you" this error show up

#### Which Operating System? 
Windows 10 1903

#### Which version of Auryo? 
![image](https://user-images.githubusercontent.com/39237127/66068062-29eab180-e54d-11e9-8a73-53e6554a8fbd.png)

**Comment by Superjo149** [comment]
Please see #221
