### ISSUE TITLE
LastFM Scrobbling

### ISSUE THREAD

**Issue by lesthack** [Superjo149/auryo#225]
# 💡 Feature request

## What do you propose
It would be great make do "scrobbling" in LastFAM

**Comment by Superjo149** [comment]
Already possible #156

**Comment by lesthack** [comment]
Nice. So, i see that snap version not is the last, right ?

**Comment by Superjo149** [comment]
Yes, something changed and it required manual verification from snapcraft. But I haven't heard anything since then. And I didn't get back to them because it thought the next version was going to be ready soon.
