### ISSUE TITLE
App doesn't launch on Wayland

### ISSUE THREAD

**Issue by cflockhart** [Superjo149/auryo#226]
# 🐛 Bug report

## What issue are you facing
App silently just exits with no error message

## Steps to reproduce
1. Open terminal
2. `/snap/bin/auryo`
<nothing>, exits

## Environment
snap version on Ubuntu 19.04, Gnome 3.32.1, Wayland session.

#### Which Operating System? 
Ubuntu 19.04

#### Which version of Auryo? 
2.3.3

Works fine in an X session. Some time ago Slack (I believe another electron app) failed in the same way but is fixed now. So I guess there may be some issue with electron apps under wayland.

**Comment by cflockhart** [comment]
I was able to build and run the github master branch AppImage for production, which gets as far as the soundcloud login, but then it just remains on the page with the login link within the app after signing in in Chrome. The AppImage for tag v2.3.3 does the same thing, however.

**Comment by Secr3ts** [comment]
@cflockhart Personally i'd try to use the *.deb file, I already done it on plenty systems (Ubuntu LTS, 19.04 & 19.10) and it worked every time. Can you try this and tell if it worked ?

**Comment by cflockhart** [comment]
@Secr3ts The 2.4.0 .deb does indeed work on 19.10 in a Wayland session. I don't get the play controls in the notifications area or media button controls, but works great otherwise.

**Comment by Secr3ts** [comment]
@cflockhart Oh i did'nt noticed this... also have you tried the apt method ? ( i don't know if it will fix it otherwise you could wait for an update because 19.10 isn't fully supported atm )

**Comment by Superjo149** [comment]
Will be followed up in #242
