### ISSUE TITLE
"For you" section spam.

### ISSUE THREAD

**Issue by Darky2018** [Superjo149/auryo#232]
When i click on "For you" section on my linux system it starts spamming "Something went wrong".

**Comment by b0wter** [comment]
Same for me. Here is the output of the about dialog:

![image](https://user-images.githubusercontent.com/614261/70126671-ce868e00-1679-11ea-9a0e-3c76dfa5143e.png)

**Comment by CNOT** [comment]
Duplicate of #221

**Comment by Superjo149** [comment]
Closed as this is a duplicate. Please go to #221 to follow up.
