### ISSUE TITLE
Right clientId, no sound

### ISSUE THREAD

**Issue by doctortee** [Superjo149/auryo#237]
# 🐛 Bug report

## What issue are you facing

When I give a clientId, music no longer plays, as if I gave a wrong clientId

http://img114.xooimage.com/files/0/6/2/capture-d-cran_20...15-16-36-56ecc8b.png

## Steps to reproduce

1. Start Auryo, go to settings
2. Go to the SoundCloud official webpage, open your "developer tools" tab, check the "network" section, find any request going to something called API, and get the clientId parameter.
3. Copy this clientId and paste it into the app settings
4. Songs will no longer play
Bonus. Restarting the app causes it to infinitely ask you to login, as mentioned in an other bugreport.

## Environment

Nothing special I guess ?

#### Which Operating System? 

Debian Testing

#### Which version of Auryo? 
2.4.0 (installed using deb package)

**Comment by Superjo149** [comment]
Allright, this is an issue with SoundCloud. Got a workaround for this. I will try and get some other small bugs in and try to ship this.



_Do you like auryo? Consider [sponsoring](https://github.com/sponsors/Superjo149)_
