### ISSUE TITLE
Automatically removed part of search string

### ISSUE THREAD

**Issue by MParvin** [Superjo149/auryo#238]
# 🐛 Bug report

## What issue are you facing
After search when I click on tracks button, automatically remove some parts of my search string.

In attached file, I searched "eminem" and when clicked on tracks, search string changed to "em"

[auryo-2020-01-15_14.57.50.zip](https://github.com/Superjo149/auryo/files/4064665/auryo-2020-01-15_14.57.50.zip)

## Steps to reproduce
Click on search box, search something then clock on tracks button.
 
#### Which Operating System? 
Ubuntu 19.10 - X 86_64

#### Which version of Auryo? 
2.4.0

**Comment by Superjo149** [comment]
I think is fixed
