### ISSUE TITLE
Release version out of date

### ISSUE THREAD

**Issue by cRaZy-bisCuiTs** [Superjo149/auryo#240]
Hey there!

Thank you very much for your dedication & work you put into the project! Unfortunately the release version (at least for Linux) is almost one year old and is 75 commits behind master repo as of now. Can we expect a new release any time soon?

**Comment by Superjo149** [comment]
It's not out of date. I just merged in my development branch last week. I just had another hiccup with the build system. I'm currently doing some final things and then it's testing time. Hope to release this or next week.

**Comment by Superjo149** [comment]
Update: https://twitter.com/Auryoapp/status/1229880714159628295

**Comment by cRaZy-bisCuiTs** [comment]
Thank you very much :)

**Comment by Superjo149** [comment]
Everything except for the snap build has been updated. There are some more issues with these. https://twitter.com/Auryoapp/status/1230260953234788352

**Comment by Superjo149** [comment]
#242

**Comment by Superjo149** [comment]
Allright, you can go ahead and update.
