### ISSUE TITLE
Unable to control player using MPRIS D-Bus

### ISSUE THREAD

**Issue by arindas** [Superjo149/auryo#247]
# 🐛 Bug report

## What issue are you facing
Unable to control the player using MPRIS D-Bus

## Steps to reproduce
Start auryo, play any song.
Run ``playerctl metadata``
Result:
```
chromium xesam:album
chromium xesam:artist
chromium xesam:title               index.html#/
```

Expected result:
Proper metadata.

Run ``playerctl pause``
Expected behaviour: player paused.
Behaviour found: No change.

## Environment
I have installed the snap version and I'm running it on Manjaro with i3-gaps wm.

```
OS: Manjaro Linux x86_64
Host: HP Pavilion x360 Convertible 14-ba0xx
Kernel: 5.5.2-1-MANJARO
Uptime: 1 hour, 4 mins
Packages: 1835 (pacman), 16 (snap)
Shell: fish 3.0.2
Resolution: 1920x1080
WM: i3
Theme: Base16-Gruvbox-Dark [GTK2/3]
Icons: oomox-Gruvbox [GTK2/3]
Terminal: st
Terminal Font: Hack
CPU: Intel i5-7200U (4) @ 3.100GHz
GPU: Intel HD Graphics 620
Memory: 2337MiB / 7836MiB
```

#### Which Operating System? 
```
OS: Manjaro Linux x86_64
Host: HP Pavilion x360 Convertible 14-ba0xx
Kernel: 5.5.2-1-MANJARO
```

#### Which version of Auryo? 
2.5.2

**Comment by arindas** [comment]
I understand that this is not a high priority issue but I would be really grateful if it's resolved. I would also be grateful if you help me identify the source of the bug.

**Comment by Superjo149** [comment]
I have been trying to fix MPRIS since the beginning of time. 😛 I thought it worked now. I'll check again.

**Comment by Superjo149** [comment]
I believe this is fixed. Please check to be sure.

**Comment by arindas** [comment]
Sorry to say this but it still doesn't work on my system.
