### ISSUE TITLE
An error occured during playback

### ISSUE THREAD

**Issue by KebabLord** [Superjo149/auryo#266]
# 🐛 Bug report

## What issue are you facing
Without client id, can't play anything. But with it only tracks from likes are unplayable. The weird thing is i can play the same song from stream or from search result, but only cant play it from likes -which is the most critic part of soundcloud experience-.

When a song cant be played receiving "An error occured during playback" with this error log:
```
[1588173451411] ERROR: Request failed with status code 401
    Error: Request failed with status code 401
        at createError (/opt/Auryo/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/opt/Auryo/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/opt/Auryo/resources/app.asar/node_modules/axios/lib/adapters/http.js:236:11)
        at IncomingMessage.emit (events.js:215:7)
        at endReadableNT (_stream_readable.js:1183:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

## Environment

Using debian 10 buster.
I live this problem only when i install auryo from my own build from repo source. When installed directly from release deb package, there was no problem and worked fine. so it turned out to be a compiling problem.
my full compiling process:  [buildauryo.log](https://github.com/Superjo149/auryo/files/4552558/buildauryo.log)

**Comment by KebabLord** [comment]
the problem is probably with typescript compiler
tsc (compiler) version: 3.8.3
typescript version: 3.2.1
```
λ tsc
node_modules/lastfm/typings/index.d.ts:9:44 - error TS1016: A required parameter cannot follow an optional parameter.

9     public request(method?: LastfmMethods, params: any): any;
                                             ~~~~~~

src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:23:18 - error TS2345: Argument of type 'false' is not assignable to parameter of type 'SetStateAction<undefined>'.

23     setIsSeeking(false);
                    ~~~~~

src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:30:17 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'SetStateAction<undefined>'.

30     setNextTime(to);
                   ~~

src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:31:18 - error TS2345: Argument of type 'true' is not assignable to parameter of type 'SetStateAction<undefined>'.

31     setIsSeeking(true);
                    ~~~~

src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:40:22 - error TS2345: Argument of type 'true' is not assignable to parameter of type 'SetStateAction<undefined>'.

40         setIsSeeking(true);
                        ~~~~

src/renderer/app/components/player/components/PlayerProgress/PlayerProgress.tsx:60:53 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.

60       <div className={styles.time}>{getReadableTime(isSeeking ? nextTime : currentTime, false, true)}</div>
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

what versions you compiled with?

**Comment by KebabLord** [comment]
holy sh*t, typescript is really a retarded language.
tested with those versions:
from 3.2 to 3.6.4 -> 39 error
3.7.2 to 3.7.3 -> 1 error
3.8.3 -> 9 error

version 3.7.3 threw only an unneccessary lastfm error so i tried to build with this one 
```
λ tsc
node_modules/lastfm/typings/index.d.ts:9:44 - error TS1016: A required parameter cannot follow an optional parameter.
9     public request(method?: LastfmMethods, params: any): any;
                                             ~~~~~~
Found 1 error.
```
still having same problem. It probably means its not about the version of typescript

**Comment by Superjo149** [comment]
Please read https://github.com/Superjo149/auryo/blob/master/.github/DEVELOPMENT.md. Just using `yarn run build` is sufficient.

**Comment by Superjo149** [comment]
Did you pehaps not set the correct env keys? https://github.com/Superjo149/auryo/blob/master/.github/DEVELOPMENT.md#env-keys

**Comment by KebabLord** [comment]
Yeah, it was the env keys. But you have to mention that while compiling your own build, you have to set keys to `.env.production` instead of `.env.development`. That DEVELOPMENT.md needs a revision.
