### ISSUE TITLE
stream limit locale

### ISSUE THREAD

**Issue by notmeta** [Superjo149/auryo#271]
# 💡 Feature request

## What do you propose
Hi there, just installed this for the first time and it looks good.
I saw when I first logged in that there was a message regarding the daily stream limit.
The message said something along the lines of "15.000 streams per day" - this should format the number with the user's locale; for me the number should be "15,000" (assuming that's the number, not 15).

## Whats steps can we take to implement it
Detect user locale somehow (not a js/ts dev) and format number that way, or switch to 15,000 as it's more widely used than 15.000

## Examples
```javascript
var number = 3500;

console.log(number.toLocaleString());
```

**Comment by Superjo149** [comment]
I've postponed any work related to Internationalization and localization. But this is fairly easy, so I'll include this in the next update
