### ISSUE TITLE
Auryo Does Not Load Full Likes Playlist

### ISSUE THREAD

**Issue by RedYoshikira** [Superjo149/auryo#275]
Only a small section of it is loaded on the client, and the rest is completely-hidden whilst it all shows on the website and mobile SoundCloud application. This persists even-after multiple application restarts and relogging into my account.

Client Version: 2.5.3
OS: Windows 10, x64
Date of Incident: May 7th, 2020

**Comment by Superjo149** [comment]
Please see #126
