### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by Superjo149** [Superjo149/auryo#312]
# 🐛 Bug report

## What issue are you facing

Due to some changes in SoundCloud's API, we are receiving 403 errors. It does not look good. Seems they have made some changes to their authorization. We are using a lot of their internal APIs, which we cannot access anymore.

## Steps to reproduce

Open Auryo

**Comment by Superjo149** [comment]
Status can be followed in this issue https://github.com/soundcloud/api/issues/14

**Comment by alkaris2** [comment]
I get either Error 401 or 403, seems to be be interchangeable between Not Authorized and Forbidden.

**Comment by Superjo149** [comment]
I am now in contact with SoundCloud via email. Will keep you posted

**Comment by Plasmabot1** [comment]
It seems to have started working now. I had the same issue a few days ago, updated nothing and now it loads.

**Comment by devilAPI** [comment]
Still dosent work

**Comment by HACKER097** [comment]
> Still dosent work

+1
