### ISSUE TITLE
Music playback automatically resumes after connecting audio device

### ISSUE THREAD

**Issue by chrismessina** [Superjo149/auryo#41]
Which OS were your using?
macOS 10.12.6

Which version of Auryo were you using?
1.1.0

Where did this error happen?
General

I've noticed that when I stop music playback and then later connect an audio device (i.e. plug in my headphones, connect to my AirPods), Auryo automatically resumes music playback without any direct interaction. 

In one case, I disconnected my headphones, put my laptop to sleep and went home. When I got home, woke my laptop, and connected my AirPods, Auryo automatically resumed playback even though it was hidden to the dock.

I'll try to observe if there are any other contributing factors to this behavior, but I would expect that playback would only resume if I hit the play/pause button explicitly.

**Comment by NA0341** [comment]
That's awesome! Many people wish this feature in many applications and you wanna get rid of it ^^
Cause for you it's a bug :)
