### ISSUE TITLE
Unlimited browser tabs opening soundcloud access confirmation page

### ISSUE THREAD

**Issue by miheenko-i** [Superjo149/auryo#42]
- Which OS were your using?
MacOs 10.12.6

- Which version of Auryo were you using?
1.1.0

- Where did this error happen?
Everytime when reconnecting to wi-fi and auryo is running

- What steps did you take to recieve this error?
Press "Confirm and continue" on one of the opened soundcloud page as fast as possible
<img width="629" alt="2017-08-15 23 21 08" src="https://user-images.githubusercontent.com/31043258/29325416-c4f880d6-8211-11e7-89bc-8bd827fede13.png">
<img width="684" alt="2017-08-15 23 30 54" src="https://user-images.githubusercontent.com/31043258/29325430-cfbd2aa8-8211-11e7-997d-675d9fed7c5a.png">

**Comment by Superjo149** [comment]
Issue resolved itself? Or should I look into it?
