### ISSUE TITLE
Following?

### ISSUE THREAD

**Issue by viruscmd** [Superjo149/auryo#47]
Mac OS 10.12.6
Auryo 1.3.0
**Where:** Artist page
**Steps taken:**

1. went to [artist page](https://soundcloud.com/thegeek) in app
2. clicked follow

Saw no indication that I  am now following the selected artist.
![image](https://user-images.githubusercontent.com/31666687/30129580-5fa70b3a-9314-11e7-8ddd-6b1ef9a01cd5.png)

**Comment by Superjo149** [comment]
@viruscmd Fixed in v1.4.0, big play queue overhaul coming, so it might take me another week to release it. Still has some bugs.
