### ISSUE TITLE
Liking a track from a profile causes a crash

### ISSUE THREAD

**Issue by chrismessina** [Superjo149/auryo#49]
- Which OS were your using?

macOS High Sierra 10.13

- Which version of Auryo were you using?

1.4.0

- Where did this error happen?

On this profile: https://soundcloud.com/ofdream

- What steps did you take to recieve this error?

Right click, like a track.

See video: [crash.mov.zip](https://github.com/Superjo149/auryo/files/1335151/crash.mov.zip)

**Comment by Superjo149** [comment]
That version of 1.4.0 has been recalled due to a major bug. This is my mistake, I have not communicated this correctly. The fixed & improved 1.4.0 will be released shortly.

**Comment by chrismessina** [comment]
Ok great. Chance of an ETA?

**Comment by Superjo149** [comment]
Within a week, just doing some final testing.
