### ISSUE TITLE
Whitescreen of death almost immediately after launching

### ISSUE THREAD

**Issue by chrismessina** [Superjo149/auryo#50]
- Which OS were your using?

10.13 (17A365)

- Which version of Auryo were you using?

1.4.2

- Where did this error happen?

After launching.

- What steps did you take to receive this error?

Launched the app. Waited a sec. See video:

[auryo.mp4.zip](https://github.com/Superjo149/auryo/files/1350187/auryo.mp4.zip)

However, once I closed the main window and relaunched it, now it seems ok? Temporary glitch?

**Comment by Superjo149** [comment]
I've seen it happen once, never been able to reproduce it since. I'm adding better error logging in the next update, hopefully these things will be found more easily.

**Comment by mohammadrafigh** [comment]
to help on this, I get this white screen if I run Auryo without a proxy, since some api's are restricted here in Iran. so I think this happens when one of the API calls fails to get the appropriate response.

**Comment by Superjo149** [comment]
Yeah, sounds about right. Error handling still isn't 100% polished.

**Comment by EpoxyD** [comment]
I get the white screen of death constantly now, running the snap on Ubuntu 17.10. It has worked before, so no idea what went wrong. I only get it after logging into my Soundcloud account. Is there any way I can see some logs in order to see what went wrong?

**Comment by Superjo149** [comment]
@EpoxyD Currently, no. But I've just resumed development, so hope to get error handling sorted in 1.5.0.

Are you using snap? possibly related to #74 (contains a fix)

**Comment by EpoxyD** [comment]
Yes, I'm using the snap. I'll try the fix, hopefully that works, thanks for the heads up!
