### ISSUE TITLE
MPRIS Integration

### ISSUE THREAD

**Issue by jens-t** [Superjo149/auryo#56]
Would be nice to have MPRIS Integration for Linux Users. So one can use something like this:
https://extensions.gnome.org/extension/55/media-player-indicator/

The Google Music Electron App integrates MPRIS already, so maybe one can find inspiration there:
https://github.com/twolfson/google-music-electron/blob/master/lib/mpris.js

Otherwise great app! I like the simplicity & clarity. I first thought a pinned Browsertab would be comfortable enough to use Soundcloud, but this is much better, Thanks!

**Comment by Superjo149** [comment]
MPRIS integration should be available, i have added this in version [1.3.0](https://github.com/Superjo149/auryo/releases/tag/v1.3.0)

**Comment by jens-t** [comment]
You're right, there was a Problem with the Extension. Thanks for the Reply. Closing the Issue.
