### ISSUE TITLE
MPRIS support (linux) for ubuntu 17.04

### ISSUE THREAD

**Issue by luispabon** [Superjo149/auryo#59]
- Which OS were your using?
Ubuntu  17.10 / Unity 7

- Which version of Auryo were you using?
1.4.2 / .deb package

I'm not entirely sure Auryo is meant to have MPRIS support, but it isn't working on Ubuntu 17.10 at the moment.

**Comment by Aaahh** [comment]
Ubuntu 17.04 / Unity 7
1.4.2
MPRIS is broken

**Comment by Aaahh** [comment]
playerctl does not register auryo as a mpris client

https://github.com/twolfson/google-music-electron/commits/master/lib/mpris.js
https://github.com/twolfson/google-music-electron/blob/master/lib/install-mpris.js
https://github.com/twolfson/google-music-electron/blob/master/lib/mpris.js

**Comment by Superjo149** [comment]
Electron-rebuild seemed to have done the trick.

**Comment by Aaahh** [comment]
Works, but:
(playerctl:2687): GLib-GIO-WARNING **: 23:08:48.512: Received property Rate with type y does not match expected type d in the expected interface

(playerctl:2687): GLib-GIO-WARNING **: 23:08:48.512: Received property Volume with type y does not match expected type d in the expected interface

(playerctl:2687): GLib-GIO-WARNING **: 23:08:48.512: Received property Position with type u does not match expected type x in the expected interface

(playerctl:2687): GLib-GIO-WARNING **: 23:08:48.512: Received property MinimumRate with type y does not match expected type d in the expected interface

(playerctl:2687): GLib-GIO-WARNING **: 23:08:48.512: Received property MaximumRate with type y does not match expected type d in the expected interface
Could not execute command: Method 'Play' returned type '(u)', but expected '()'

**Comment by Superjo149** [comment]
What system did you use to run these tests on?

**Comment by Superjo149** [comment]
I do not believe I can do anything about this. And it's just warnings so i'm going to close this.
