### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by luispabon** [Superjo149/auryo#61]
When submitting an issue please answer following question alongside your description. Please also submit screenshots if possible.

- Which OS were your using?
Ubuntu 17.10 / Unity 7

- Which version of Auryo were you using?
1.4.2 / deb

CPU usage is too high:
  * idle (no track playing): ~25%
  * playback: ~45%

That's % of a single core off an i5-4200M.

**Comment by rafaelcgo** [comment]
Are we able to read the source code?
We might get a glimpse what is happening if we could do that. (Hope it's not mining cryptos)

**Comment by Superjo149** [comment]
@rafaelcgo Currently not thinking about making it open-source, but no it's not mining cryptos (I thought about it tho). Electron is known for it's high system resource usage. I'll be debugging and profiling the app for the next update.

**Comment by luispabon** [comment]
I don't think it's an electron issue per se. vscode is electron and cpu usage while idle is exactly 0%.

**Comment by Superjo149** [comment]
@luispabon Yes, but I'm the only one working on this, vscode is support by a whole team. By default, electron is power hungry. I haven't made any improvements yet regarding performance.

**Comment by Superjo149** [comment]
Those numbers are pretty crazy tho, I have not ran into such high numbers yet.

**Comment by Superjo149** [comment]
No, you're 100% correct. But it's likely part of the problem. The other part is just probably my coding. I'm not a Electron or React expert so I'll have to do some profiling to see what could be causing this. Unlike vscode I'm just on my own, I bet they have some electron wizards.

**Comment by Moumouls** [comment]
<img width="698" alt="pwer_comsuption" src="https://user-images.githubusercontent.com/27959372/35467685-f6e96d4a-0311-11e8-9718-d574cde57400.png">

On Mac 2016, i confirm an high power consumption ! On another window the app take 11 point of energy wich is pretty impressive for an audio App :/

I think on the UI we can have an improvement ( 40 points of energy ) and in an away mode ( on another window ) it will be interesting to have a profile for determinate if it's a UI problem or a network/decode problem !

For the others, it's impossible to hide a mining cryptos algorithm. When you check network I/O of the app, it's too low for mining cryptos ;) (Unless the algo is really very light)

**Comment by Superjo149** [comment]
@Moumouls It'll be my top priority for [v1.5.0](https://github.com/Superjo149/auryo/milestone/10). Development should resume next week.

**Comment by Superjo149** [comment]
I have made some improvements, I do not have side-by-side comparisons, but I believe to have located the main source of the high CPU usage. Like mentioned before, it wIll be released in v1.5.0

**Comment by Superjo149** [comment]
In 1.5.0, there was still pretty high CPU usage. This has 100% been fixed in 2.2.x

**Comment by Ulisses1478** [comment]
I'm on 2.3.3 and auryo is consuming 100% of 1 cpu core

**Comment by Superjo149** [comment]
@Ulisses1478 Could you make a seperate issue for this and specify maybe how long it has been open and if it was previously playing. If you closed your pc between this time. The more info the easier for me to track this bug.

**Comment by Ulisses1478** [comment]
> @Ulisses1478 
I will make a better analysis and I post but this will take a bit of time.
