### ISSUE TITLE
To big icons and fonts (4k monitor)

### ISSUE THREAD

**Issue by BessonovEvgeniy** [Superjo149/auryo#62]

**Comment by BessonovEvgeniy** [comment]
Please find below screenshot
https://drive.google.com/open?id=1HVc7xRID6ULUAR4ka15pXkRuMopR4P-N

**Comment by Superjo149** [comment]
Oh boy, that's seems to be a bit too big

**Comment by BessonovEvgeniy** [comment]
Ok, I can try my one if any fixes. Maybe the best way to allows users to scale UI items itself.
