### ISSUE TITLE
White screen after searching

### ISSUE THREAD

**Issue by colinstrachan** [Superjo149/auryo#63]
Hey, so I really love the idea of this software, however I'm completely unable to search for music which makes it almost useless.  I type in my keywords into the search box and results start to load in the sidebar, but as soon as I move towards the results to select something the whole screen goes white and the app becomes unresponsive.  I then have to close it and restart.

Surprised not to see any other comments about this.

Any ideas?
Thanks!

- Which OS were your using?
Ubuntu 16.04 LTS

- Which version of Auryo were you using?
1.4.3

- Where did this error happen?
Search

- What steps did you take to recieve this error?
Typed in some keywords and moved the mouse towards the search results.

**Comment by colinstrachan** [comment]
Apologies, it doesn't actually happen with all searches.  Try searching for 'Atish' and see if you get the same issue.

**Comment by Superjo149** [comment]
Possibly related to #50, #54 also describes this issue

**Comment by Superjo149** [comment]
It can indeed be reproduced by typing "Atish", weird but thanks for adding these steps. I'll investigate.

**Comment by colinstrachan** [comment]
Oops, didn't see those others for some reason. Glad I could provide some extra info.

**Comment by juliuszfedyk** [comment]
Same issue on Mac Os 10.11.6

**Comment by imyxh** [comment]
I also get a white screen when adding any track to a playlist. No messages to console or anything.
Should I create a separate issue?

**Comment by Superjo149** [comment]
@imyxh No need, I'll be investigating the white screen issue as a whole.

**Comment by solomonkitumba** [comment]
white screen of death when adding item to play list

**Comment by chaosKP** [comment]
I'm getting the same issue on Ubuntu 17.10 x64.
But it only happens sometimes not everytime.

**Comment by voxwill** [comment]
Same here, **Love the software**, but **crashes** most times on **search**. 

I'm able to search if I only write two letters at a time, and let it load in between each character. Not ideal.
