### ISSUE TITLE
Crash on adding song to playlist

### ISSUE THREAD

**Issue by chrismessina** [Superjo149/auryo#64]
- Which OS were your using?

macOS 10.13.1 (17B1003)

- Which version of Auryo were you using?

1.4.3

- Where did this error happen?

See screencast

- What steps did you take to recieve this error?

See screencast

[auryo-crash.mp4.zip](https://github.com/Superjo149/auryo/files/1528931/auryo-crash.mp4.zip)

**Comment by balaianu** [comment]
I can confirm this, also.

- Which OS were your using?
Ubuntu 15.10

- Which version of Auryo were you using?
1.4.3 (AppImage)

- Where did this error happen?
In the single song screen

- What steps did you take to recieve this error?
Clicked the "Add to playlist" button. The crash occurs right after some pop-up seams to initiate, then the screen goes blank (white) and the app needs to be closed and re-opened.

**Comment by ekevjn** [comment]
I faced the same issues
+ OS: Ubuntu 16.04
+ Auryo version: 1.4.3 (AppImage)
+ Error happen in album screen, stream screen,...
+ I clicked the "Add to playlist" button and the app crash.

**Comment by iVegas** [comment]
- Which OS were your using? - Ubuntu 17.10

- Which version of Auryo were you using? - 1.4.3

- Where did this error happen? - Trying to add the track to the playlist.

- What steps did you take to recieve this error?

**STR**:

- Launch the app: You will see stream view;

- Choose track by clicking on the title of the track: You will see the track view;

- Add the track to the playlist by clicking on "Add to playlist" button: You will see the animation of appearing the list of playlists and at the end of animation whitescreen will appear.

**Comment by NA0341** [comment]
- OS - Ubuntu 16.04.3
- Version: 1.4.3 (snap)
- Error @ adding track to a playlist in any section
- results in: Playlist pops up and then the main process¹ (called auryo) dies leaving the type-gpu and the second auryo - process running
- !**no** warning or **message from the system** will be shown. Means that the system **doesn't intended** this as a **crash**?
Shell output: `na0341@na0341:~$ auryo`
`Gtk-Message: Failed to load module "overlay-scrollbar"`
`Gtk-Message: Failed to load module "gail"`
`Gtk-Message: Failed to load module "atk-bridge"`
`Gtk-Message: Failed to load module "canberra-gtk-module"`
`Start: 1096.125ms`

I'll write this comment to complete the known information about the error.
+ Screenshots:
- **auryo¹ ~60-140 MiB** System Monitor - Info
![image](https://user-images.githubusercontent.com/26059513/37807497-0de163cc-2e46-11e8-96b9-52a5a39a3857.png)
- **auryo ~50 MiB** System Monitor - Info
![image](https://user-images.githubusercontent.com/26059513/37807852-d80df1f0-2e47-11e8-919c-b2122ca5f51d.png)
- **auryo --type=gpu-process** System Monitor - Info
![image](https://user-images.githubusercontent.com/26059513/37807870-ef889de4-2e47-11e8-9b1a-797c493d81d9.png)
- when maximized the application uses up to **52%** of my **2.13 GHZ dualCore - Processor!** (I've seen that it only supports one cpu :)
![image](https://user-images.githubusercontent.com/26059513/37807572-7cb48266-2e46-11e8-9e3e-f34efc507477.png)
- **!only** if minimized the cpu - usage is **instantly zero!**
![image](https://user-images.githubusercontent.com/26059513/37808008-ad1598bc-2e48-11e8-99ad-a1ef0dde46da.png)

¹ I think that this is the main - process cause it uses the most memory and CPU
