### ISSUE TITLE
AUR Package [Installation]

### ISSUE THREAD

**Issue by lll2yu** [Superjo149/auryo#72]
Hello there,
I made an AUR(Arch User Repository) package for arch linux for this software.
You can check that here -> https://aur.archlinux.org/packages/auryo/ 
It would be helpful for other users if you mention it somewhere on the download page.
Thank You.

**Comment by Superjo149** [comment]
@lll2yu cool, is there any way I can push to it directly?

**Comment by lll2yu** [comment]
@Superjo149Ya sure, I'll add you as a co-maintainer. What's your AUR username?

**Comment by Superjo149** [comment]
@lll2yu Just created an account, username is @Sneljo

**Comment by lll2yu** [comment]
@Superjo149 I added you as co-maintainer. If you have any AUR related query,you can dm me on Twitter or telegram @lll2yu.

**Comment by lll2yu** [comment]
@Superjo149 Since the source code for the application is released now, it's possible to build from the application from a release source tarball. 
To comply with Arch Linux naming standards the package `auryo` needs to be moved to `auryo-bin` as its build against binary release.
According to arch linux package naming standards 

- `auryo` - Build using source tarball.
- `auryo-bin` - Build using release binary.
- `auryo-git` - Build against latest commit.

I have already submitted request to move `auryo` to `auryo-bin`, it will take some time to reflect the changes. I have already added `auryo` and `auryo-git` as conflicting packages, so anyone can pick those up and maintain them without affecting `auryo-bin`.

Please alter your automatic AUR build/push process accordingly.

**Comment by Superjo149** [comment]
@lll2yu Thanks again for supporting me on this, I'm not familiar with AUR at all. I'll change it in travis.

**Comment by lll2yu** [comment]
@Superjo149 The AUR build fails because of checksum mismatch. This is because the sha256sums are not getting updated by travis build. I updated the checksum in PKGBUILD for now but on next travis build it will get wrong again as such. Maybe you can fix that in travis. 

Alternatively,I would suggest signing your binaries with a pgp key and providing a .asc file along to verify integrity. This would remove the need to compare checksums in all.
