### ISSUE TITLE
Fails to log in to soundcloud after launching the application

### ISSUE THREAD

**Issue by binegra** [Superjo149/auryo#73]
- Which OS were your using?
Elementary OS 0.4.1 Loki (based on Ubuntu 16.04.3 LTS)
- Which version of Auryo were you using?
1.4.3
- Where did this error happen?
Immeditaly after launching the app
- What steps did you take to recieve this error?
Just launched Auryo and it keeps logging in without any success or response

This is the output I got launching from the terminal:
```
adam@lenovo:~$ auryo 
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Start: 422.364ms
```
It's worth to mention that it was working well until I had to renew my password, but I am not sure, if I logged in back with the new one or it's went wrong before I can do so.

![screenshot from 2018-01-28 10 43 21](https://user-images.githubusercontent.com/14187206/35480867-4397b974-0418-11e8-8507-0c231ec72f12.png)

**Comment by binegra** [comment]
So, what's the problem? Am I the only one facing this situation?

**Comment by Superjo149** [comment]
Might be related to #50 and #63, I'm currently investigating the issue. I'm just guessing at this point, In 1.4.2 logging isn't really done properly so I'm not able to track down the problem easily. But there's hope, 1.5.0 will contain a bunch of bug fixes. Just hold on. 🐎

**Comment by binegra** [comment]
Thanks and keep up the good work!
I like your application btw and I would keep using it, once this misbehaviour is solved
