### ISSUE TITLE
[Request] Hide reposts toggle

### ISSUE THREAD

**Issue by renaudll** [Superjo149/auryo#75]
Hi, 

Really nice app!
However one key missing feature is prevent me from using it, the ability to hide reposts.

I'm aware that this is not a default soundcloud feature but without it browsing the soundcloud stream is hard, especially when you follow a lot of artist and are only interested in their original content.
https://soundcloudcommunity.com/desktop-230066/is-there-a-way-to-hide-reposts-of-other-users-in-my-stream-6492170/index5.html

Currently I'm able to do it using a chrome extension:
https://chrome.google.com/webstore/detail/repost-toggle-for-soundcl/amimeafgcnfidkeknebnfdblmmekifem?utm_source=chrome-app-launcher-info-dialog

Thanks for your consideration!

- Which OS were your using?
Linux pop-os 4.13.0-32-generic

- Which version of Auryo were you using?
1.4.3

- Where did this error happen?
n/a

- What steps did you take to recieve this error?
n/a

**Comment by Superjo149** [comment]
I will add it in 1.5.0, thanks for you input.
