### ISSUE TITLE
What's the license and what's the reason why the source code isn't available?

### ISSUE THREAD

**Issue by GabMus** [Superjo149/auryo#77]
I happened to see this app featured in a blog I follow, and I got weirded out by the fact that it's not open source.

After looking at the website and at this dummy (issues only apparently) github repo, I even realized there is no licensing for this app.

So I am asking here:

- Why are you not releasing the source code of this app?
- What is the current license this app is released under?

**Comment by GabMus** [comment]
Ok, understood.

I get the reasons behind your choice, but I'm afraid I won't be using this
app soon. I just wanted a clarification on the license and eula, and your
answer was more than enough. Nevertheless, I value the degree of freedom of
the apps I use, and I accept to use proprietary software only if I have no
viable alternative (ie: nvidia drivers, steam for linux and its games), but
I don't think that auryo (that by the way looks very promising) has
anything more than other SoundCloud clients or the web client itself to
justify its license.

What I'm trying to say is that the degree of freedom of apps is as
important as its design or stability. Just like me, many other people will
probably feel the same and not use this app, and that's really a shame in
my opinion.

You can still have a free software app and monetize it, there's nothing
wrong about it, so I suggest you to reconsider your app's licensing , and
maybe next time we'll be talking it will be a pull request rather than a
meta issue :)

**Comment by Superjo149** [comment]
Update: It's now open-source.
