### ISSUE TITLE
System-wide media controls

### ISSUE THREAD

**Issue by pandaxtc** [Superjo149/auryo#78]
Are there any plans to add system-wide and/or native media controls, like this?

![media_controls](https://user-images.githubusercontent.com/22638037/37872586-86c5c56a-2fbf-11e8-8696-15c3caef31fc.PNG)

I know there are hotkeys that function when the app is in the foreground, but I'm wondering about hotkeys that work at all times.

Thanks!

**Comment by Superjo149** [comment]
I think this is an issue in windows 8.x, works fine in windows 10. I'll look Into it. Also a keymap will be included in the app next update

**Comment by dragxtcon** [comment]
I'm actually on Win10! Sorry, I didn't include my OS because I assumed I was giving a feature request.

**Comment by Superjo149** [comment]
This feature will be tracked here #87
