### ISSUE TITLE
[Expected behaviour] Displayed duration in grid view for tracks ≥ 60 minutes

### ISSUE THREAD

**Issue by snorreflorre** [Superjo149/auryo#79]
# Actual behaviour
For tracks ≥ 60 minutes (e.g. DJ-sets or podcasts) the duration displayed in grid view has the format `H:i`, whereas the duration for shorter tracks shows `i:s`
# Expected behaviour
The duration for tracks ≥ 60 minutes is displayed in the format `H:i:s`
# Example
The original track with a duration of 1:06:42 can be found [here](https://soundcloud.com/diynamic-music/diynamic-radio-show-november-2017-by-andy-bros).
![image](https://user-images.githubusercontent.com/3702251/38286598-7e2fa31c-37c6-11e8-9b64-be260395054a.png)
# System specification
Auryo 1.4.3 on Ubuntu 17.10

**Comment by Superjo149** [comment]
fixed in 1.5.0, still working on this 😁
