### ISSUE TITLE
Feature request: filter reposts

### ISSUE THREAD

**Issue by rusins** [Superjo149/auryo#80]
This isn't something that's possible even in Soundcloud's web interface, but it would be extremely useful if it was possible to filter out songs in the feed that were reposts/forwards/whatever Soundcloud calls them. That way you could listen to the things in your feed that are solely from the artists you follow. :)

**Comment by renaudll** [comment]
Hi rusins, I asked this on #75. It should be available on 1.5.0. I don't have any information about a release date so let's keep our fingers crossed!

**Comment by rusins** [comment]
Ah, sorry, not sure how I missed that! Will close this issue in that case.
