### ISSUE TITLE
[Requests] Dark Theme and Keyboard Media Controls Support

### ISSUE THREAD

**Issue by kreh** [Superjo149/auryo#83]
It would be awesome for the nocturnal listeners to have a dark mode so it wouldn't be blinding to look for something within the program!

Also, I see that when I hover over the program, it has the pause, forward and back buttons, akin to Spotify. To enhance the ease, it'll be great to have media control support!

**Comment by Superjo149** [comment]
Dark mode is **definitely** coming. As for media control support, i'm still looking into this for windows. I have not found much information on this.

**Comment by kreh** [comment]
Thank you for adding mcs!

**Comment by Superjo149** [comment]
Going to make a seperate issue for dark mode. Windows media control is fixed.
