### ISSUE TITLE
Feature to display current song playing into a txt for OBS and XSplot

### ISSUE THREAD

**Issue by XDChunk** [Superjo149/auryo#92]
title says it all really.

**Comment by KebabLord** [comment]
this would be an amazing feature. I also want to display current playing song on my status bar so i need to pull current playing song. Is there a way exist? Since it been already 2 years since this feature request, is it already implemented?

**Comment by KebabLord** [comment]
its just 
```
import fs from 'fs';
fs.writeFileSync('/tmp/auryo_status.log', track.title + "\n" + track.user.username);
```
should been already implemented

**Comment by Superjo149** [comment]
@KebabLord Feel free to create a PR for this.

**Comment by KebabLord** [comment]
@Superjo149 Superjo149/auryo#270

**Comment by Superjo149** [comment]
Will add this in the next minor release. Will have a look if I can fix some other small things. Otherwise I will just push this fix.
