### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Superjo149** [Superjo149/auryo#97]
Matte black all the things

**Comment by alistairholmes** [comment]
A Dark theme would be really appreciated :blush:

**Comment by Superjo149** [comment]
@alistairholmes  It's already finished. I'm just finishing up chromecast support and I'll be publishing this release soon.

**Comment by awsms** [comment]
What colours did you pick for the dark theme? Black/orange?

**Comment by f0rmatme** [comment]
still in progress? can this get added soon?  :)

**Comment by fluffynuts** [comment]
Just built my own Auryo 2.5.0 on my machine and dark mode is <3 <3 <3

**Comment by fluffynuts** [comment]
(btw, blue is really nice too)

**Comment by fluffynuts** [comment]
I think that some accessible themes would be nice to have in there:
- dark, with higher contrast, larger fonts (if possible)
  - there are people for whom dark-on-light is just a bleed of light over everything; light-on-dark is better, but they still need more contrast, and often larger stuff
- light, with larger fonts if possible
  - for people who don't have the light-bleed issue, but perhaps just need more light to see things, and larger bits on-screen

I don't see a way (right) now to modify font-sizes, but I think it could be done. Would anyone be interested in PRs for this?

**Comment by Superjo149** [comment]
Blue is wonderfull 😁

Op 4 okt. 2019 09:49 schreef Davyd McColl <notifications@github.com>:

(btw, blue is really nice too)
